import img1 from "@assets/1.png"
import img2 from "@assets/2.png"
import img3 from "@assets/3.png"
import img4 from "@assets/4.png"
import img5 from "@assets/5.png"
import img6 from "@assets/6.png"
import img7 from "@assets/7.png"
import img8 from "@assets/8.png"
import img9 from "@assets/9.png"
import img10 from "@assets/10.png"
import img11 from "@assets/11.png"
import img12 from "@assets/13.png"
import img13 from "@assets/14.png"
import img14 from "@assets/15.png"
import img15 from "@assets/16.png"
import img16 from "@assets/17.png"
import img17 from "@assets/18.png"
import img18 from "@assets/19.png"
import img19 from "@assets/20.png"
import img20 from "@assets/21.png"
import img21 from "@assets/22.png"
import img22 from "@assets/23.png"
import img23 from "@assets/24.png"
import img24 from "@assets/25.png"
import img25 from "@assets/26.png"
import img26 from "@assets/27.png"
import img27 from "@assets/28.png"
import img28 from "@assets/29.png"
import img29 from "@assets/30.png"
import img30 from "@assets/31.png"
import img31 from "@assets/32.png"
import upload from '@assets/great_wave_remix_randal_roberts_fb.png'


const images = [
    { source: img1 },
    { source: img2 },
    { source: img3 },
    { source: img4 },
    { source: img5 },
    { source: img6 },
    { source: img7 },
    { source: img8 },
    { source: img9 },
    { source: img10 },
    { source: img11 },
    { source: img12 },
    { source: img13 },
    { source: img14 },
    { source: img15 },
    { source: img16 },
    { source: img17 },
    { source: img18 },
    { source: img19 },
    { source: img20 },
    { source: img21 },
    { source: img22 },
    { source: img23 },
    { source: img24 },
    { source: img25 },
    { source: img26 },
    { source: img27 },
    { source: img28 },
    { source: img29 },
    { source: img30 },
    { source: img31 },
    { source: img21 },
  ]
 

export default images