# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Bottega' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Bottega

  target 'Bottega-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'react-native-fbsdk', :path => '../node_modules/react-native-fbsdk'

  end

  target 'BottegaTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'Bottega-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Bottega-tvOS



end

pod 'Bolts'
pod 'FBSDKLoginKit'
pod 'FBSDKShareKit'
pod 'FBSDKCoreKit'
